### PR TITLE
Implement the Wall Collision

### PR DESCRIPTION
**Pull request by dalli12**
- I modified pacman to hit the wall without passing through the wall.
- Also, pacman will not avoid the dot.

### CODE REVIEW

**Comment by SojeongLee** [comment]
It's very nice, but I think that it will be better if the pacman's movement more smoothly!!

**Comment by dalli12** [comment]
I improved that pacman can move more smoothly.
Please check again. 😃

**Comment by SojeongLee** [comment]
It's works more smoothly. I agree merge!!

**Comment by qpab7722** [comment]
good! agree merge

**Comment by yeonsoy** [comment]
brilliant! I agree merge it too. :smile:

**Pull request merged**
