### PR TITLE
Fixed Screen and Viewpoint

### PR DESCRIPTION
**Pull request by dalli12**
## Fixed Screen
- welcome screen and result screen are modified to avoid duplication.  I think this will make it look more neat.

## Fixed Viewpoint
- I implemented the first person view. I fixed the viewpoint of 3D screen look like a first person view, and I modified it to follow pacman's position.

### CODE REVIEW

**Comment by SojeongLee** [comment]
I check it. It works very well!!
The camera is tracking the pacman well.
You are a really good programmer~~!!

**Comment by qpab7722** [comment]
incredible!
i agree merge .
you did a hard job!

**Comment by SojeongLee** [comment]
It is reflected lately modifications to keyboard input.
I agree merge!!

**Comment by yeonsoy** [comment]
Great! It's works good. thanks for your work. I agree to merge it.

**Pull request merged**
